### ISSUE TITLE
way to identify if it was deleted

### ISSUE THREAD

**Issue by ghost** [Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins#12] opened 2019-09-09 02:14 UTC
maybe make so things are identified if they are deleted or not like say turning it red like when a message doesent send properly (sorry if its not ment to be in issues i dont use github alot)

**Comment by RainGH** [comment] 2019-09-09 23:33
I believe deleted messages were appearing in red when I initially installed the plugin yesterday. There seems to have been a Discord update overnight and deleted messages no longer appear in red, they instead remain as white, and therefore look exactly like normal messages. 
Perhaps there's something preventing deleted messages becoming red now?

**Comment by ShiiroSan** [comment] 2019-09-11 06:19
Latest update broke NDM. Just wait for update.

**Comment by Laiteux** [comment] 2019-09-13 05:31
Any ETA? It's been a few days already...

**Comment by wefalltomorrow** [comment] 2019-09-14 13:52
Can confirm, stopped working here as well.

**Comment by neroxqq** [comment] 2019-09-14 14:15
how to fix it by urself?

**Comment by Furav** [comment] 2019-09-21 15:50
Still like this for me, any way to fix it yourself?

**Comment by JTAG7371** [comment] 2019-09-23 01:33
To fix so you can tell when messages were deleted: Open NoDeleteMessages.plugin.js and go to line 262 and replace ".da-message" with ".da-container". That will make the text red again when the message has been deleted.

![image](https://user-images.githubusercontent.com/4204011/65397746-83631b80-ddaa-11e9-9c12-1901852e6766.png)

**Comment by Laiteux** [comment] 2019-09-23 01:37
Here's a working version: https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/blob/abc55a2eb64df91d4f620027ad886237ffc9bdd8/NoDeleteMessages/NoDeleteMessages.plugin.js

**Comment by wefalltomorrow** [comment] 2019-09-26 09:45
[**@Laiteux**](https://github.com/Laiteux) commented on [23 Sep 2019, 11:37 GMT+10](https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/issues/12#issuecomment-533938464 "2019-09-23T01:37:47Z - Replied by Github Reply Comments"):
> Here's a working version: [https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/blob/abc55a2eb64df91d4f620027ad886237ffc9bdd8/NoDeleteMessages/NoDeleteMessages.plugin.js](https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/blob/abc55a2eb64df91d4f620027ad886237ffc9bdd8/NoDeleteMessages/NoDeleteMessages.plugin.js)

Sadly doesn't work for me, messages still aren't red when deleted.

**Comment by Laiteux** [comment] 2019-09-27 05:44
> [**@Laiteux**](https://github.com/Laiteux) commented on [23 Sep 2019, 11:37 GMT+10](https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/issues/12#issuecomment-533938464):
> 
> > Here's a working version: https://github.com/Mega-Mewthree/BetterDiscordTrustedUnofficialPlugins/blob/abc55a2eb64df91d4f620027ad886237ffc9bdd8/NoDeleteMessages/NoDeleteMessages.plugin.js
> 
> Sadly doesn't work for me, messages still aren't red when deleted.

Works as intended on my side:
![](https://laiteux.dev/prgfhz)
https://hastebin.com/ozoyanotel.js

**Comment by wefalltomorrow** [comment] 2019-09-27 08:46
Working for me now, not sure what changed or fixed it but thanks!

**Comment by Laiteux** [comment] 2019-10-18 03:58
Seems like it broke again (message becomes transparent when edited).

**Comment by Hiroshi18** [comment] 2019-10-18 17:19
It was fixed on this PR #18 made by ShiiroSan

You could manually use it manually for now till the maintainer accept the PR

Go to your plugin folder and copy and paste the code in https://github.com/ShiiroSan/BetterDiscordTrustedUnofficialPlugins/blob/master/NoDeleteMessages/NoDeleteMessages.plugin.js to you local plugin file NoDeleteMessages.plugin.js t

**Comment by Mega-Mewthree** [comment] 2019-11-16 19:46
Fixed with merge of #18.

**Closed as completed by Mega-Mewthree** 2019-11-16 19:46 UTC
